

# MONGODB
#MONGODB_HOST='172.17.0.2'
MONGODB_HOST='mongodb'
MONGODB_PORT=27017

#PostgresDB
#DATABASE_USER = "postgres"
DATABASE_USER = "airflow"
#DATABASE_PASSWORD = "postgres"
DATABASE_PASSWORD = "airflow"
#DATABASE_HOST = "172.17.0.3"
DATABASE_HOST = "postgres"
DATABASE_PORT = 5432
DATABASE_DB_NAME = "airflow"


#- POSTGRES_USER=airflow
#- POSTGRES_PASSWORD=airflow
#- POSTGRES_DB=airflow
